### ISSUE TITLE
We’d like to recommend two of our recent papers that might fit well into this collection

### ISSUE THREAD

**Issue by ZiyiZhang27** [xie-lab-ml/awesome-alignment-of-diffusion-models#2]
Hi,

Thank you for creating this awesome repository on the alignment of diffusion models! It’s a great resource for the community.

We’d like to recommend two of our recent papers that might fit well into this collection:

- Confronting Reward Overoptimization for Diffusion Models: A Perspective of Inductive and Primacy Biases, ICML 2024, [[pdf]](https://openreview.net/pdf?id=v2o9rRJcEv)
- Aligning Few-Step Diffusion Models with Dense Reward Difference Learning, arXiv 2024, [[pdf]](https://arxiv.org/pdf/2411.11727)

Best regards!

**Comment by Buhua-Liu** [comment]
Merged. Thanks!

**Comment by ZiyiZhang27** [comment]
Thank you for including our work! However, we noticed that our method, "Aligning Few-Step Diffusion Models with Dense Reward Difference Learning," has been categorized under DPO, which might be a misunderstanding. Our approach is actually closer to RLHF, as it explicitly optimizes for a reward signal rather than relying on data-driven preferences. The most relevant work to ours is "PRDP: Proximal Reward Difference Prediction for Large-Scale Reward Finetuning of Diffusion Models," which you categorized under RLHF. Given this similarity, it might be more fitting to classify our work under RLHF as well.

Wish you all the best with your work!
